import { useRouter } from "next/router";
import Head from "next/head";
import HomeServiceItem from "../../components/home/ServiceItem";
import service3 from "../../public/service3.jpg";
import service5 from "../../public/service5.jpg";
import service6 from "../../public/service6.jpg";
import Link from "next/link";
import axios from "axios";
import { API_URL } from "../../constants";
import { useEffect, useState } from "react";
import Loader from "../../components/Loader";

export default function ServiceSubPage() {

    const [data, setData] = useState();
    const [loading, setLoading] = useState(true);
    const router = useRouter();
    const id = router.query.pid;

    const api = `${API_URL}/services?slug=${id}&acf_format=standard`;
    useEffect(() => {
        if (id) {
            axios.get(api)
                .then((res) => setData(res.data[0]))
                .finally(() => setLoading(false));
        }
    }, [id]);

    if (loading) {
        return <Loader />
    }

    return (
        <div className="servive-single">
            <Head>
                <title>{data.title.rendered} | Geesa.am</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="container">
                <h1 style={{ textAlign: "left" }}>{data.title.rendered}</h1>
                <p style={{ textAlign: "left" }}>{data.acf.small_content}</p>
                <h5>Ջրամեկուսացման ենթաբաժինները</h5>
                <div className="row">
                    {
                        data.acf.sub_services.map((item, key) => {
                            return <div key={key} className="col-md-3">
                                <HomeServiceItem
                                    image={item.thumbnail_image}
                                    title={item.sub_services[0].post_title}
                                    key={key}
                                    url={`category/${item.sub_services[0].ID}`}
                                />
                            </div>
                        })
                    }
                </div>
            </div>
        </div>
    )
}

  