import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HomeAbout from '../components/home/About'
import HomeBanner from '../components/home/Banner'
import HomeJobs from '../components/home/Jobs'
import HomeServices from '../components/home/Services'
import styles from '../styles/Home.module.css'
import axios from "axios";
import { API_URL } from '../constants'

export default function Home({ data, services, works }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Գլխավոր | Geesa.am</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <HomeBanner data={data} />
        <HomeServices services={services} />
        <HomeAbout data={data} />
        <HomeJobs works={works} />
      </main>
    </div>
  )
}


export async function getServerSideProps() {
  const res = await axios.get(`${API_URL}/pages/10?acf_format=standard`);
  const services = await axios.get(`${API_URL}/services?acf_format=standard`);
  const works = await axios.get(`${API_URL}/works?acf_format=standard`);

  return {
    props: { data: res.data, services: services.data, works: works.data },
  };
}

