import Head from "next/head";
import HomeServiceItem from "../components/home/ServiceItem";

import axios from "axios";
import { API_URL } from "../constants";

export default function Services({data, services}) {
    return (
        <div className="services-page">
            <Head>
                <title>Ծառայություններ | Geesa.am</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="container">
                <h1>{data.acf.title}</h1>
                <p>{data.acf.text}</p>
                <div className="row">
                {
                        services.map((service, key) => {
                            return <div key={key} className="col-md-4">
                                <HomeServiceItem image={service.acf.banner_image}  title={service.title.rendered} url={service.slug} id={service.id} />
                            </div>
                        })
                    }
                </div>
            </div>
        </div>
    )
}

export async function getServerSideProps(context) {
    const res = await axios.get(`${API_URL}/pages/95?acf_format=standard`);
    const services = await axios.get(`${API_URL}/services?acf_format=standard`);

    return {
      props: { data: res.data, services: services.data },
    };
  }
  