import Head from "next/head";
import HomeJobItem from "../components/home/JobItem";
// Import Images
import job1 from "../public/job1.jpg";
import job2 from "../public/job2.jpg";
import job3 from "../public/job3.jpg";
import job4 from "../public/job4.jpg";
import job5 from "../public/job5.jpg";
import job6 from "../public/job6.jpg";
import job7 from "../public/job7.jpg";
import job8 from "../public/job8.jpg";
import axios from "axios";
import { API_URL } from "../constants";

export default function Works({ data, works }) {
    
    return (
        <div className="works">
            <Head>
                <title>Աշխատանքներ | Geesa.am</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="container">
                <h1>{data.acf.title}</h1>
                <p>{data.acf.text}</p>
                <div className="row">
                {
                        works.map((work, key) => {
                            return (
                                <div key={key} className="col-md-3">
                                <HomeJobItem
                                    alt="Alt"
                                    src={work.acf.image}
                                    title={work.title.rendered}
                                />
                            </div>
                            )
                        })
                    }
                </div>
            </div>
        </div>
    )
}


export async function getServerSideProps(context) {
    const res = await axios.get(`${API_URL}/pages/87?acf_format=standard`);
    const works = await axios.get(`${API_URL}/works?acf_format=standard`);

    return {
      props: { data: res.data, works: works.data },
    };
  }
  